version: "3"
services:
  reservation-bear:
    image: ghcr.io/eistbaren/server:latest
    platform: linux/amd64
    build:
      context: .
    ports: 
      - "8080:8080"
    environment:
      - SPRING_MAIL_HOST=mymail.website.com
      - SPRING_MAIL_USERNAME=myemail@website.com
      - SPRING_MAIL_PASSWORD=secretPassword123

