name: Run gradle tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# https://stackoverflow.com/questions/67344181/how-to-use-github-actions-bot-for-testing-gradle-java

jobs:
  test:
    name: Gradle Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run tests
        run: ./gradlew test --tests "*"
