name: "Push to bitbucket"

on:
  push:
    # Just for testing, will be changed to main!!
    branches: [workflow/pushToBitbucket]

permissions:
  contens: read

jobs:
  pushToBitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: Clone backend repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: github
          submodules: true
      
      - name: Clone bitbucket repo
        uses: actions/checkout@v3
        with:
          repository: "ssh://git@bitbucket.ase.in.tum.de:7999/EIST22T02/eist22t02-eistbaeren27.git"
          path: bitbucket
          # The ssh-key belongs to Dorians account
          ssh-key: ${{ secrets.BITBUCKET_SSH_KEY }}
          ssh-strict: false
          submodules: true

      - name: Get properties of last commit
        run: |
          export COMMIT_USER=$(git log -n 1 --pretty=format:%an)
          echo "COMMIT_USER=$COMMIT_USER" >> $GITHUB_ENV

          export COMMIT_EMAIL=$(git log -n 1 --pretty=format:%ae)
          echo "COMMIT_EMAIL=$COMMIT_EMAIL" >> $GITHUB_ENV

          export COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Setup SSH Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.BITBUCKET_SSH_KEY }}"

      - name: Move .git folder from bitbucket to github repo
        run: |
          rm -rf ./github/.git
          cp -r ./bitbucket/.git ./github

      - name: Commit and push bitbucket repo
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          # Go into github, because we copied the bitbucket .git folder,
          # so technically it's now the bitbucket repo :)
          cd github

          git config user.name "$COMMIT_USER"
          git config user.email "$COMMIT_EMAIL"
          git add *
          git commit -a -m "$COMMIT_MESSAGE"
          git push
